### ISSUE TITLE
Could not find gem 'jekyll-edit-link' in any of the gem sources listed in your Gemfile.

### ISSUE THREAD

**Issue by stevemoser** [benbalter/jekyll-edit-link#1]
404 at https://rubygems.org/gems/jekyll-edit-link

Has this been superseded by https://github.com/jekyll/github-metadata?

**Comment by benbalter** [comment]
Yes. See https://github.com/jekyll/github-metadata/blob/master/lib/jekyll-github-metadata/edit-link-tag.rb.
